title: rayvn
description: A bash shared library ecosystem
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
url: https://rayvn.ink

nav_external_links:
  - title: rayvn on GitHub
    url: https://github.com/phoggy/rayvn
  - title: valt on GitHub
    url: https://github.com/phoggy/valt
  - title: wardn on GitHub
    url: https://github.com/phoggy/wardn
